### ISSUE TITLE
 No such file or directory: '../dataset/Duke/bounding_box_train/0001_c2_f0046182.jpg'

### ISSUE THREAD

**Issue by Mickeybaby** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#20]
When I run the 'python unsupervised.py'
(kertf) mickey@a208-System-Product-Name:~/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning/PUL$ python unsupervised.py
/home/mickey/miniconda3/envs/kertf/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Using TensorFlow backend.
2019-06-12 21:30:56.332595: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-12 21:30:56.429239: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-12 21:30:56.429564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.90GiB freeMemory: 11.59GiB
2019-06-12 21:30:56.429594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "unsupervised.py", line 63, in <module>
    img = image.load_img(os.path.join(TRAIN, img), target_size=[224, 224])
  File "/home/mickey/.local/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 110, in load_img
    img = pil_image.open(path)
  File "/home/mickey/miniconda3/envs/kertf/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/Duke/bounding_box_train/0001_c2_f0046182.jpg'
The bounding box directory is not found in the dataset.
Can you give me some advice?
Best wishes to you!

**Comment by hehefan** [comment]
Hi @Mickeybaby, large-scale datasets are a little large. You need to download them by yourself.
Please go to http://www.liangzheng.com.cn/Datasets.html for details.

**Comment by Mickeybaby** [comment]
Thank you very much!
